#!/bin/sh

if [ ! -d "vendor/laravel" ]; then
    composer install --no-interaction --prefer-dist
fi

if [ ! -f ".env" ]; then
    cp .env.example .env
    php artisan key:generate
fi

php artisan migrate --force

exec php artisan serve --host=0.0.0.0 --port=80